# Generated by Django 5.0.2 on 2024-03-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FIleUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.TextField()),
                ('upload_id', models.TextField()),
                ('file_size', models.CharField(max_length=250)),
            ],
        ),
    ]
