# Generated by Django 5.0.2 on 2024-03-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='upload_completed',
            field=models.BooleanField(default=False),
        ),
    ]
