# Generated by Django 4.1 on 2024-04-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system_management", "0002_fileupload_upload_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileupload",
            name="object_key",
            field=models.TextField(default=""),
        ),
    ]
