# Generated by Django 4.1 on 2024-04-17 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("system_management", "0003_fileupload_object_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileMetaData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("part_number", models.CharField(max_length=250)),
                ("start", models.CharField(max_length=250)),
                ("end", models.CharField(max_length=250)),
                (
                    "file_upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="system_management.fileupload",
                    ),
                ),
            ],
        ),
    ]
